<a href="https://colab.research.google.com/github/raj1807600-ux/new-repo/blob/main/assign2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

We will use Seaborn’s built-in tips dataset to practice identifying numerical, categorical, discrete, continuous, nominal, and ordinal data. Because classifying columns by their meaning is more useful than blindly trusting their data types, this exercise includes both inspection and interpretation.

Complete the following tasks using Python, Pandas, and Seaborn.

1.Load the Tips dataset into a DataFrame.

In [ ]:
import pandas as pd
import seaborn as sns

In [ ]:
df=sns.load_dataset("tips")

In [ ]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

2
.
Display the first five rows.

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

3
.
Check the data types of all columns using df.dtypes.

In [ ]:
df.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

4
.
Filter customers whose total_bill is greater than 20.

In [ ]:
selected=df[df["total_bill"]>20]

In [ ]:
selected

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
237       32.83  1.17    Male    Yes  Sat  Dinner     2
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[97 rows x 7 columns]

5.Explain why size is numerical but day is categorical

In [ ]:
#size:-
#      size — it means Numerical and Discrete
# size column batata hai ki table par kitne log baitheaa hain.

In [ ]:
# day — Categorical and Nominal hotaaaaa hai

#or  day column batata hai ki customer kis din kaha  gaya.